title: F' Worlds Fantasy Adventure Group
author: f_worlds
description: Fantasy Is Fun

highlighter: null
permalink: /:title

url: http://voidnologo.com/shadowrun
baseurl: /shadowrun

# Custom options:
# color_scheme: azul|ruby|amber|avocado
# color_scheme: avocado
